### ISSUE TITLE
Messages when apps are offline

### ISSUE THREAD

**Issue by KeithBoynton** [KSemenenko/GoogleAnalyticsForXamarinForms#39]
One area of this package I'm not clear about is what the behaviour is when apps are offline or have poor/no connectivity? Presumably those messages get lost or is there some kind of message cache so the messages are sent later when connectivity has been re-established?

**Comment by KSemenenko** [comment]
all is saved to a file in a local folder. And after the advent of the Internet, I try to send everything

**Comment by KeithBoynton** [comment]
That's really good to hear, thank you

**Comment by DennisWelu** [comment]
@KSemenenko What happens if it's an unhandled exception and the app crashes without getting the crash payload successfully sent? Is that payload still persisted locally and resent when the app is started again and the Internet is available? 

Tracing through the code I don't see where that is happening but perhaps I am missing it. In the iOS application where I am testing this I've debugged through the code and see where the [request is being sent](https://github.com/KSemenenko/GoogleAnalyticsForXamarinForms/blob/master/GoogleAnalytics.Shared/GAServiceManager.cs#L245) but the application dies before it gets to the next line. And never see the exception showing up in the analytics dashboard either.

**Comment by KSemenenko** [comment]
in theory, when you send payload and the sending did not end, it is saved in a text file.
but maybe something is going wrong @DennisWelu 
This is a good place to fix it

**Comment by DennisWelu** [comment]
Ok thanks @KSemenenko . I did not see it happening. I'm not very familiar with the code base - can you point out an example in the code where it is writing to the text file you mention?

**Comment by DennisWelu** [comment]
@KSemenenko I spent some time looking over the code and tracking through it. I cannot find anywhere where it records unsent data to a text file. I do see this: https://github.com/KSemenenko/GoogleAnalyticsForXamarinForms/blob/master/GoogleAnalytics.Shared/GAServiceManager.cs#L287 It looks like maybe there's a comment indicating the location where something like that might happen? Other than that, am I missing something?
